### ISSUE TITLE
[BUG] A path bug concerning the image folder

### ISSUE THREAD

**Issue by WenyinWei** [alyssaq/3Dreconstruction#4]
Hello @alyssaq , there is a small bug concerning the image folder. In the `README.md`, readers are told to put images under `imgs/dino`, but a better one is `imgs/dinos`. Otherwise, the path bug would cause the interruption.

The repository is awesome and I have stared it. Thanks a lot!

**Comment by alyssaq** [comment]
Thanks! Ive updated the readme. Glad you're finding it helpful :smile:
